### PR TITLE
Fix brandautocomplete

### PR DESCRIPTION
**Pull request by fretje**
I've been playing a bit more with the brandautocomplete, and finally got it to work by using the onafterrender method instead, like you see in this pr...

Please check it and if it's okay I can cleanup the unused code in the products view...

### CODE REVIEW

**Comment by iammukeshm** [comment]
Looks fine to me

**Review by iammukeshm — APPROVED** [review]

**Comment by fretje** [comment]
Okay it's cleaned up... there's still something strange going on with the image upload but I haven't touched that ;-)

image

Also I've seen there's a "clear" button now, but not when editing an image... 
I mean it is, but only after choosing another image, and when you then clear it, the original image is there again...

**Comment by iammukeshm** [comment]
This long gray bar comes when the image mentioned in the DB is no longer found in the File System. Was not able to find a fix for this. It's something related to MudBlazor too.

Clear button only clears the temporary image the was loaded only to the client app and not to server. As of now Image deletion I have not added. It kinda requires some design changes in the way we process data. Maybe have to add a flag to delete the image while sending the update request to server.

**Comment by fretje** [comment]
the grey bar is also on the "create product" dialog like you see... in that case there isn't anything in the database yet...

about deletion... when a new image is saved, the old one should be deleted (but I think this already happens)... it should also be deleted when the image is cleared (so when no image is sent... or indeed maybe with a flag if that isn't possible).

but yeah... design wise, I think the image upload should be a separate call with only the file for a particular product... in that case you can always delete the previous one (or even add the possibility to add/remove multiple images)...

We also need to factor out that upload file functionality into separate services/components, both on the client and on the server, as there is now already repeating code in products and the account page for that both on the client and on the server...
And I guess you want to add upload functionality for brands as well in the future (or any other entity that users of the template might create).

**Pull request merged**
