### PR TITLE
Use NSwag to automatically generate Api Client and DTO classes

### PR DESCRIPTION
**Pull request by fretje**
Before this works, [this pull request over on the api repo](https://github.com/fullstackhero/dotnet-webapi-boilerplate/pull/291) needs to be merged first.

I've added some infrastructure to automatically generate c# client classes to call the api. It is now a "PreBuildEvent". There might probably be a better place to put this. Or maybe just a target that doesn't run automatically (should then be possible to call manually when needed with `dotnet run -t NSwag`).

I've also updated the brands and the products pages to use those generated client (and dto) classes.

I've added in the options (nswag.json) that the generated client classes need to have Interfaces and that the Interface needs to derive from IApiService. This way the generated clients are automatically injected into DI with the already existing             `AutoRegisterInterfaces<IApiService>()` call.
There's more nswag.json options there we can explore and maybe leverage. It's also possible to add custom functionality as all the classes are generated as partial classes, and they have some partial methods like preparerequest, processresponse, ... There's also an option to derive them from a shared base class. 

Draft for now so you can already have a look, and if ok, I'll update the rest of the application to use the generated classes. 

This should basically eliminate the "Shared.DTOs" project here or on the api repository for that matter...

### CODE REVIEW

**Comment by fretje** [comment]
Ok, had to remove the aftertargets from the NSwag target as it broke the ci build here on github (as there the swagger.json is not available on localhost:5001 of course).

The c# clients can manually be regenerated by running:

**Comment by fretje** [comment]
We really need to find something to keep ourselves from having to write repeating code like this:

        if (response.Succeeded)
        {
            if (response.Messages?.Count > 0)
                _snackBar.Add(response.Messages.First(), Severity.Success);
            else
                _snackBar.Add(_localizer["Success"], Severity.Success);
            MudDialog.Close();
        }
        else
        {
            if (response.Messages?.Count > 0)
            {
                foreach (string message in response.Messages)
                {
                    _snackBar.Add(message, Severity.Error);
                }
            }
        }

We actually also need to catch ApiExceptions now for non 200 responses. I don't think the previous implementation took care of that either. If there was a temporary disconnect with the server for instance.

**Comment by fretje** [comment]
Ok, so after cleaning up the Shared project... The only things that are left now are the things that could really be shared between the api and this repo. Those are basically our claim names (also some extensions that use the claimnames for easy access from iclaimsprincipal), our permission names and the notifications sent over signalr.

There's also still the "Wrapper" folder, but that's now only used by IAuthenticationService... I think we can easily eliminate the use of that wrapper there as well. (This is probably for another discussion, but I don't really see the point of the use of that wrapper... I might be missing something ;-)).

**Review by iammukeshm — APPROVED** [review]

**Comment by frankyjquintero** [comment]
wonderful contribution

**Pull request merged**
