### PR TITLE
Generic EntityTable

### PR DESCRIPTION
**Pull request by fretje**
Merry Christmass! :-D

This is a first attempt at a generic "entitymanager". Applied to both the Brands and the Products views.
They both are functioning exactly the same like before, which can definitely still use some work as some features are not yet implemented. But at least you can do it now in one spot ;-)

Still thinking about the api and the naming... looking for feedback.

We'll probably have to add functionality/customization as we go... also probably split it up into more separate components... in the end I imagine it should be usable on the roles and users screen as well...

Look how nice and clean `Brands.razor` has become (even small enough to put it in one file in stead of with code behind) ;-)

### CODE REVIEW

**Comment by iammukeshm** [comment]
Cool, I had a similar approach in a previous project where we made the Table Component Generic. The one challenge I saw is that, when the Table has to be customized (like adding a new button, or changing the color of a row based on some conditions, etc), the generic approach doesn't do very well. 

For ex, the AuditLogs table cannot use this generic approach, right? What would be your suggestion?

**Review by iammukeshm — APPROVED** [review]

**Comment by fretje** [comment]
Yeah, for now, I've taken the road of least resistance for implementing both products and brands... they are quite basic so the rowtemplate is not customizable, but in the end it should be... also the toolbarcontent, ...

That's also what I meant with "adding functionality/customization options as we go" and splitting it up in multiple smaller sub-components over time... For instance the search field, and the "reload" and "create" buttons... we should never have to copy that specific markup again (and have to change it everywhere if it needs to be changed)...

**Comment by fretje** [comment]
Roles has been done... (non server side filtering/sorting and extra actions button)

**Comment by fretje** [comment]
AuditLogs done...

**Comment by fretje** [comment]
Users done as well... 
There's only one thing that isn't working (as far as I see), and that's the passwordVisibilityToggle... 

Can't seem to figure out why ;-s

**Comment by fretje** [comment]
Ok, found the culprit... apparently have to explicitly do a `StateHasChanged` on the dialog... added a convenience method on the context for that (`AddEditModalForceRender`).

With that, I think it's ready for review ;-)

**Review by iammukeshm — APPROVED** [review]

**Comment by iammukeshm** [comment]
I think the control level validation is still not available? I am able to see it via login page as well, also via brand / product forms

**Comment by iammukeshm** [comment]
BTW, the code looks very clean and minimal at the first glance. Will dig deep and let you know.

**Comment by fretje** [comment]
Can you clarify what you mean with control level validation? Is it the 400 result you're talking about?

For me it's working on the login page, also on the add new user screen (due to the 400 response I just added over on the api project). For products and brands, that 400 response will also have to be added.

image

**Comment by iammukeshm** [comment]
Try to submit an entirely blank form. You should be able to reproduce the issue.

**Comment by iammukeshm** [comment]
The DataAnnotations of the FshApi Client code get triggered but don't reflect back to the mud control.

**Comment by iammukeshm** [comment]
I guess adding the NullHandling = Ignore property to the Serializer should fix this. That's for Server-side validation. But then again, we still have to figure out Local Validation. The DataAnnotationsValidator that you have added, what's its role?

**Comment by iammukeshm** [comment]
Also, if NSWAG could read the fluentValidation Rules (of API), it should be able to generate better client code. And this should also fix the local validation I beleive.

**Comment by fretje** [comment]
Aaah, ok, now I see what you mean. The reason is the nullability... because on the RegisterRequest type on the server, the properties are annotated with the [Required] attribute, they apparently get generated with non nullable properties on the client. 

I see they even get the same annotations applied. That's magnificent... (hadn't realized that before).

But somehow they *don't* get triggered... I'll have a look why...

**Comment by fretje** [comment]
Ok, I see the problem. The AddEditModal is not working with a RegisterRequest, but rather with a UserDetailsDto (as that's the base entity of the whole "EntityTable")... 

The CreateAsync method on the Users view uses mapster to map the UserDetailsDto to the RegisterRequest... I'll have a look if I can trigger the validation after that...

Otherwise I might have to introduce another (or rather 2) new TypeParameters for the registerrequest and updaterequest types...

**Comment by fretje** [comment]
NSwag doesn't read the fluentvalidations, but it does read the dataannotations apparently (that's what I didn't realize), and adds all those validations to the jsonschema supplied in the openapi spec.

There's a package apparently to also process fluentvalidations:

https://github.com/zymlabs/nswag-fluentvalidation

we'll have to check that out!

**Comment by fretje** [comment]
See #58

**Comment by iammukeshm** [comment]
Also, i think it is necessary to copy over the fluentValidator rules to the wasm project as well, in case someone wants to add additional validation rules for entity creation and stuff.

**Comment by iammukeshm** [comment]
So, instead of dataAnnotations validator we can make use of the local FluentValidator and remove the validation dependency with NSWAG's generated code.

**Comment by iammukeshm** [comment]
Let's continue the chat here - https://github.com/fullstackhero/blazor-wasm-boilerplate/issues/59

**Pull request merged**
